/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAccess_tokenFromDiscriminatorValue, createContinueEscapedFromDiscriminatorValue, createErrorInvalidRequestFromDiscriminatorValue, serializeAccess_token, serializeContinueEscaped, type Access_token, type ContinueEscaped, type ErrorInvalidRequest } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /continue/{id}
 */
export interface ContinueItemRequestBuilder extends BaseRequestBuilder<ContinueItemRequestBuilder> {
    /**
     * Cancel a grant request or delete a grant client side.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ErrorInvalidRequest} error when the service returns a 404 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Continue a grant request during or after user interaction.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ContinuePostResponse>}
     */
     post(body: ContinuePostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ContinuePostResponse | undefined>;
    /**
     * Cancel a grant request or delete a grant client side.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Continue a grant request during or after user interaction.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ContinuePostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface ContinuePostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The interaction reference generated for thisinteraction by the AS.
     */
    interactRef?: string | null;
}
export interface ContinuePostResponse extends AdditionalDataHolder, Parsable {
    /**
     * A single access token or set of access tokens that the client instance can use to call the RS on behalf of the RO.
     */
    accessToken?: Access_token | null;
    /**
     * If the AS determines that the request can be continued with additional requests, it responds with the continue field.
     */
    continueEscaped?: ContinueEscaped | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ContinuePostRequestBody}
 */
// @ts-ignore
export function createContinuePostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoContinuePostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ContinuePostResponse}
 */
// @ts-ignore
export function createContinuePostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoContinuePostResponse;
}
/**
 * The deserialization information for the current model
 * @param ContinuePostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoContinuePostRequestBody(continuePostRequestBody: Partial<ContinuePostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "interact_ref": n => { continuePostRequestBody.interactRef = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ContinuePostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoContinuePostResponse(continuePostResponse: Partial<ContinuePostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "access_token": n => { continuePostResponse.accessToken = n.getObjectValue<Access_token>(createAccess_tokenFromDiscriminatorValue); },
        "continue": n => { continuePostResponse.continueEscaped = n.getObjectValue<ContinueEscaped>(createContinueEscapedFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param ContinuePostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeContinuePostRequestBody(writer: SerializationWriter, continuePostRequestBody: Partial<ContinuePostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!continuePostRequestBody || isSerializingDerivedType) { return; }
    writer.writeStringValue("interact_ref", continuePostRequestBody.interactRef);
    writer.writeAdditionalData(continuePostRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param ContinuePostResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeContinuePostResponse(writer: SerializationWriter, continuePostResponse: Partial<ContinuePostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!continuePostResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Access_token>("access_token", continuePostResponse.accessToken, serializeAccess_token);
    writer.writeObjectValue<ContinueEscaped>("continue", continuePostResponse.continueEscaped, serializeContinueEscaped);
    writer.writeAdditionalData(continuePostResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const ContinueItemRequestBuilderUriTemplate = "{+baseurl}/continue/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ContinueItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: ContinueItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            404: createErrorInvalidRequestFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    post: {
        uriTemplate: ContinueItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createContinuePostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeContinuePostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
