/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, createOutgoingPaymentFromDiscriminatorValue, type ErrorResponse, type OutgoingPayment } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /outgoing-payments/{id}
 */
export interface OutgoingPaymentsItemRequestBuilder extends BaseRequestBuilder<OutgoingPaymentsItemRequestBuilder> {
    /**
     * A client can fetch the latest state of an outgoing payment.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OutgoingPayment>}
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     * @throws {ErrorResponse} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OutgoingPayment | undefined>;
    /**
     * A client can fetch the latest state of an outgoing payment.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OutgoingPaymentsItemRequestBuilderUriTemplate = "{+baseurl}/outgoing-payments/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const OutgoingPaymentsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OutgoingPaymentsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOutgoingPaymentFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
