/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, createQuoteFromDiscriminatorValue, type ErrorResponse, type Quote } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /quotes/{id}
 */
export interface QuotesItemRequestBuilder extends BaseRequestBuilder<QuotesItemRequestBuilder> {
    /**
     * A client can fetch the latest state of a quote.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Quote>}
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     * @throws {ErrorResponse} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Quote | undefined>;
    /**
     * A client can fetch the latest state of a quote.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QuotesItemRequestBuilderUriTemplate = "{+baseurl}/quotes/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const QuotesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: QuotesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQuoteFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
