/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ContinueItemRequestBuilderRequestsMetadata, type ContinueItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /continue
 */
export interface ContinueRequestBuilder extends BaseRequestBuilder<ContinueRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.continue.item collection
     * @param id Unique identifier of the item
     * @returns {ContinueItemRequestBuilder}
     */
     byId(id: string) : ContinueItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ContinueRequestBuilderUriTemplate = "{+baseurl}/continue";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ContinueRequestBuilderNavigationMetadata: Record<Exclude<keyof ContinueRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ContinueItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/* tslint:enable */
/* eslint-enable */
