/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ContinueRequestBuilderNavigationMetadata, type ContinueRequestBuilder } from './continueEscaped/index.js';
// @ts-ignore
import { createAccess_tokenFromDiscriminatorValue, createAccessIncomingFromDiscriminatorValue, createAccessOutgoingFromDiscriminatorValue, createAccessQuoteFromDiscriminatorValue, createContinueEscapedFromDiscriminatorValue, createErrorInvalidClientFromDiscriminatorValue, createErrorRequestDeniedFromDiscriminatorValue, createInteractRequestFromDiscriminatorValue, createInteractResponseFromDiscriminatorValue, deserializeIntoAccessIncoming, deserializeIntoAccessOutgoing, deserializeIntoAccessQuote, serializeAccess_token, serializeAccessIncoming, serializeAccessOutgoing, serializeAccessQuote, serializeContinueEscaped, serializeInteractRequest, serializeInteractResponse, type Access_token, type AccessIncoming, type AccessOutgoing, type AccessQuote, type ContinueEscaped, type ErrorInvalidClient, type ErrorRequestDenied, type InteractRequest, type InteractResponse } from './models/index.js';
// @ts-ignore
import { TokenRequestBuilderNavigationMetadata, type TokenRequestBuilder } from './token/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestAdapter, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

export type AccessItem = AccessIncoming | AccessOutgoing | AccessQuote;
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface AuthClient extends BaseRequestBuilder<AuthClient> {
    /**
     * The continue property
     */
    get continueEscaped(): ContinueRequestBuilder;
    /**
     * The token property
     */
    get token(): TokenRequestBuilder;
    /**
     * Make a new grant request
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PostResponseMember1 | PostResponseMember2>}
     * @throws {ErrorInvalidClient} error when the service returns a 401 status code
     * @throws {ErrorRequestDenied} error when the service returns a 500 status code
     */
     post(body: PostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PostResponseMember1 | PostResponseMember2 | undefined>;
    /**
     * Make a new grant request
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: PostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AccessIncoming | AccessOutgoing | AccessQuote}
 */
// @ts-ignore
export function createAccessItemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccessItem;
}
/**
 * Instantiates a new {@link AuthClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createAuthClient(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
        parseNodeFactoryRegistry.registerDefaultDeserializer(JsonParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(TextParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(FormParseNodeFactory, backingStoreFactory);
    }
    
    if (serializationWriterFactory.registerDefaultSerializer) {
        serializationWriterFactory.registerDefaultSerializer(JsonSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(TextSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(FormSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(MultipartSerializationWriterFactory);
    }
    
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://auth.interledger-test.dev";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<AuthClient>(requestAdapter, pathParameters, AuthClientNavigationMetadata, AuthClientRequestsMetadata);
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostRequestBody_access_token}
 */
// @ts-ignore
export function createPostRequestBody_access_tokenFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostRequestBody_access_token;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostRequestBody}
 */
// @ts-ignore
export function createPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostResponseMember1 | PostResponseMember2}
 */
// @ts-ignore
export function createPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostResponseMember1}
 */
// @ts-ignore
export function createPostResponseMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostResponseMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostResponseMember2}
 */
// @ts-ignore
export function createPostResponseMember2FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostResponseMember2;
}
/**
 * The deserialization information for the current model
 * @param AccessItem The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccessItem(accessItem: Partial<AccessIncoming | AccessOutgoing | AccessQuote> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoAccessIncoming(accessItem as AccessIncoming),
        ...deserializeIntoAccessOutgoing(accessItem as AccessOutgoing),
        ...deserializeIntoAccessQuote(accessItem as AccessQuote),
    }
}
/**
 * The deserialization information for the current model
 * @param PostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostRequestBody(postRequestBody: Partial<PostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "access_token": n => { postRequestBody.accessToken = n.getObjectValue<PostRequestBody_access_token>(createPostRequestBody_access_tokenFromDiscriminatorValue); },
        "client": n => { postRequestBody.client = n.getStringValue(); },
        "interact": n => { postRequestBody.interact = n.getObjectValue<InteractRequest>(createInteractRequestFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PostRequestBody_access_token The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostRequestBody_access_token(postRequestBody_access_token: Partial<PostRequestBody_access_token> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "access": n => { postRequestBody_access_token.access = n.getCollectionOfObjectValues<AccessIncoming>(createAccessIncomingFromDiscriminatorValue) ?? n.getCollectionOfObjectValues<AccessOutgoing>(createAccessOutgoingFromDiscriminatorValue) ?? n.getCollectionOfObjectValues<AccessQuote>(createAccessQuoteFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostResponse(postResponse: Partial<PostResponseMember1 | PostResponseMember2> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoPostResponseMember1(postResponse as PostResponseMember1),
        ...deserializeIntoPostResponseMember2(postResponse as PostResponseMember2),
    }
}
/**
 * The deserialization information for the current model
 * @param PostResponseMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostResponseMember1(postResponseMember1: Partial<PostResponseMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "continue": n => { postResponseMember1.continueEscaped = n.getObjectValue<ContinueEscaped>(createContinueEscapedFromDiscriminatorValue); },
        "interact": n => { postResponseMember1.interact = n.getObjectValue<InteractResponse>(createInteractResponseFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PostResponseMember2 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostResponseMember2(postResponseMember2: Partial<PostResponseMember2> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "access_token": n => { postResponseMember2.accessToken = n.getObjectValue<Access_token>(createAccess_tokenFromDiscriminatorValue); },
        "continue": n => { postResponseMember2.continueEscaped = n.getObjectValue<ContinueEscaped>(createContinueEscapedFromDiscriminatorValue); },
    }
}
export interface PostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The access_token property
     */
    accessToken?: PostRequestBody_access_token | null;
    /**
     * Wallet address of the client instance that is making this request.When sending a non-continuation request to the AS, the client instance MUST identify itself by including the client field of the request and by signing the request.A JSON Web Key Set document, including the public key that the client instance will use to protect this request and any continuation requests at the AS and any user-facing information about the client instance used in interactions, MUST be available at the wallet address + `/jwks.json` url.If sending a grant initiation request that requires RO interaction, the wallet address MUST serve necessary client display information.
     */
    client?: string | null;
    /**
     * The client instance declares the parameters for interaction methods that it can support using the interact field.
     */
    interact?: InteractRequest | null;
}
export interface PostRequestBody_access_token extends AdditionalDataHolder, Parsable {
    /**
     * A description of the rights associated with this access token.
     */
    access?: (AccessIncoming | AccessOutgoing | AccessQuote)[] | null;
}
export type PostResponse = PostResponseMember1 | PostResponseMember2;
export interface PostResponseMember1 extends AdditionalDataHolder, Parsable {
    /**
     * If the AS determines that the request can be continued with additional requests, it responds with the continue field.
     */
    continueEscaped?: ContinueEscaped | null;
    /**
     * The interact property
     */
    interact?: InteractResponse | null;
}
export interface PostResponseMember2 extends AdditionalDataHolder, Parsable {
    /**
     * A single access token or set of access tokens that the client instance can use to call the RS on behalf of the RO.
     */
    accessToken?: Access_token | null;
    /**
     * If the AS determines that the request can be continued with additional requests, it responds with the continue field.
     */
    continueEscaped?: ContinueEscaped | null;
}
/**
 * Serializes information the current object
 * @param AccessItem The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccessItem(writer: SerializationWriter, accessItem: Partial<AccessIncoming | AccessOutgoing | AccessQuote> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeAccessIncoming(writer, accessItem as AccessIncoming);
    serializeAccessOutgoing(writer, accessItem as AccessOutgoing);
    serializeAccessQuote(writer, accessItem as AccessQuote);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostRequestBody(writer: SerializationWriter, postRequestBody: Partial<PostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!postRequestBody || isSerializingDerivedType) { return; }
    writer.writeObjectValue<PostRequestBody_access_token>("access_token", postRequestBody.accessToken, serializePostRequestBody_access_token);
    writer.writeStringValue("client", postRequestBody.client);
    writer.writeObjectValue<InteractRequest>("interact", postRequestBody.interact, serializeInteractRequest);
    writer.writeAdditionalData(postRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PostRequestBody_access_token The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostRequestBody_access_token(writer: SerializationWriter, postRequestBody_access_token: Partial<PostRequestBody_access_token> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!postRequestBody_access_token || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<AccessIncoming | AccessOutgoing | AccessQuote>("access", postRequestBody_access_token.access, serializeAccessItem);
    writer.writeAdditionalData(postRequestBody_access_token.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PostResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostResponse(writer: SerializationWriter, postResponse: Partial<PostResponseMember1 | PostResponseMember2> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializePostResponseMember1(writer, postResponse as PostResponseMember1);
    serializePostResponseMember2(writer, postResponse as PostResponseMember2);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PostResponseMember1 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostResponseMember1(writer: SerializationWriter, postResponseMember1: Partial<PostResponseMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!postResponseMember1 || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ContinueEscaped>("continue", postResponseMember1.continueEscaped, serializeContinueEscaped);
    writer.writeObjectValue<InteractResponse>("interact", postResponseMember1.interact, serializeInteractResponse);
    writer.writeAdditionalData(postResponseMember1.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PostResponseMember2 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostResponseMember2(writer: SerializationWriter, postResponseMember2: Partial<PostResponseMember2> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!postResponseMember2 || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Access_token>("access_token", postResponseMember2.accessToken, serializeAccess_token);
    writer.writeObjectValue<ContinueEscaped>("continue", postResponseMember2.continueEscaped, serializeContinueEscaped);
    writer.writeAdditionalData(postResponseMember2.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const AuthClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuthClientNavigationMetadata: Record<Exclude<keyof AuthClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    continueEscaped: {
        navigationMetadata: ContinueRequestBuilderNavigationMetadata,
    },
    token: {
        navigationMetadata: TokenRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AuthClientRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AuthClientUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorInvalidClientFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorRequestDeniedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
