/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAmountFromDiscriminatorValue, createErrorResponseFromDiscriminatorValue, createQuoteFromDiscriminatorValue, PaymentMethod, PaymentMethodObject, serializeAmount, serializeQuote, type Amount, type ErrorResponse, type Quote } from '../models/index.js';
// @ts-ignore
import { QuotesItemRequestBuilderRequestsMetadata, type QuotesItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuotesPostRequestBodyMember1 | QuotesPostRequestBodyMember2 | QuotesPostRequestBodyMember3}
 */
// @ts-ignore
export function createQuotesPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuotesPostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuotesPostRequestBodyMember1}
 */
// @ts-ignore
export function createQuotesPostRequestBodyMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuotesPostRequestBodyMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuotesPostRequestBodyMember2}
 */
// @ts-ignore
export function createQuotesPostRequestBodyMember2FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuotesPostRequestBodyMember2;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuotesPostRequestBodyMember3}
 */
// @ts-ignore
export function createQuotesPostRequestBodyMember3FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuotesPostRequestBodyMember3;
}
/**
 * The deserialization information for the current model
 * @param QuotesPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuotesPostRequestBody(quotesPostRequestBody: Partial<QuotesPostRequestBodyMember1 | QuotesPostRequestBodyMember2 | QuotesPostRequestBodyMember3> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoQuotesPostRequestBodyMember1(quotesPostRequestBody as QuotesPostRequestBodyMember1),
        ...deserializeIntoQuotesPostRequestBodyMember2(quotesPostRequestBody as QuotesPostRequestBodyMember2),
        ...deserializeIntoQuotesPostRequestBodyMember3(quotesPostRequestBody as QuotesPostRequestBodyMember3),
    }
}
/**
 * The deserialization information for the current model
 * @param QuotesPostRequestBodyMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuotesPostRequestBodyMember1(quotesPostRequestBodyMember1: Partial<QuotesPostRequestBodyMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "method": n => { quotesPostRequestBodyMember1.method = n.getEnumValue<PaymentMethod>(PaymentMethodObject); },
        "receiver": n => { quotesPostRequestBodyMember1.receiver = n.getStringValue(); },
        "walletAddress": n => { quotesPostRequestBodyMember1.walletAddress = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QuotesPostRequestBodyMember2 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuotesPostRequestBodyMember2(quotesPostRequestBodyMember2: Partial<QuotesPostRequestBodyMember2> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "method": n => { quotesPostRequestBodyMember2.method = n.getEnumValue<PaymentMethod>(PaymentMethodObject); },
        "receiveAmount": n => { quotesPostRequestBodyMember2.receiveAmount = n.getObjectValue<Amount>(createAmountFromDiscriminatorValue); },
        "receiver": n => { quotesPostRequestBodyMember2.receiver = n.getStringValue(); },
        "walletAddress": n => { quotesPostRequestBodyMember2.walletAddress = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param QuotesPostRequestBodyMember3 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuotesPostRequestBodyMember3(quotesPostRequestBodyMember3: Partial<QuotesPostRequestBodyMember3> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "debitAmount": n => { quotesPostRequestBodyMember3.debitAmount = n.getObjectValue<Amount>(createAmountFromDiscriminatorValue); },
        "method": n => { quotesPostRequestBodyMember3.method = n.getEnumValue<PaymentMethod>(PaymentMethodObject); },
        "receiver": n => { quotesPostRequestBodyMember3.receiver = n.getStringValue(); },
        "walletAddress": n => { quotesPostRequestBodyMember3.walletAddress = n.getStringValue(); },
    }
}
export type QuotesPostRequestBody = QuotesPostRequestBodyMember1 | QuotesPostRequestBodyMember2 | QuotesPostRequestBodyMember3;
/**
 * Create quote for an `receiver` that is an Incoming Payment with an `incomingAmount`
 */
export interface QuotesPostRequestBodyMember1 extends Parsable {
    /**
     * The method property
     */
    method?: PaymentMethod | null;
    /**
     * The URL of the incoming payment that is being paid.
     */
    receiver?: string | null;
    /**
     * The URL of an Open Payments wallet address
     */
    walletAddress?: string | null;
}
/**
 * Create a quote with a fixed-receive amount
 */
export interface QuotesPostRequestBodyMember2 extends Parsable {
    /**
     * The method property
     */
    method?: PaymentMethod | null;
    /**
     * The fixed amount that would be paid into the receiving wallet address given a successful outgoing payment.
     */
    receiveAmount?: Amount | null;
    /**
     * The URL of the incoming payment that is being paid.
     */
    receiver?: string | null;
    /**
     * The URL of an Open Payments wallet address
     */
    walletAddress?: string | null;
}
/**
 * Create a quote with a fixed-send amount
 */
export interface QuotesPostRequestBodyMember3 extends Parsable {
    /**
     * The fixed amount that would be sent from the sending wallet address given a successful outgoing payment.
     */
    debitAmount?: Amount | null;
    /**
     * The method property
     */
    method?: PaymentMethod | null;
    /**
     * The URL of the incoming payment that is being paid.
     */
    receiver?: string | null;
    /**
     * The URL of an Open Payments wallet address
     */
    walletAddress?: string | null;
}
/**
 * Create a new quote at the wallet address.
 */
export interface QuotesRequestBuilder extends BaseRequestBuilder<QuotesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.quotes.item collection
     * @param id Sub-resource identifier
     * @returns {QuotesItemRequestBuilder}
     */
     byId(id: string) : QuotesItemRequestBuilder;
    /**
     * A **quote** is a sub-resource of a wallet address. It represents a quote for a payment from the wallet address.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Quote>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     */
     post(body: QuotesPostRequestBodyMember1 | QuotesPostRequestBodyMember2 | QuotesPostRequestBodyMember3, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Quote | undefined>;
    /**
     * A **quote** is a sub-resource of a wallet address. It represents a quote for a payment from the wallet address.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QuotesPostRequestBodyMember1 | QuotesPostRequestBodyMember2 | QuotesPostRequestBodyMember3, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QuotesPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuotesPostRequestBody(writer: SerializationWriter, quotesPostRequestBody: Partial<QuotesPostRequestBodyMember1 | QuotesPostRequestBodyMember2 | QuotesPostRequestBodyMember3> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeQuotesPostRequestBodyMember1(writer, quotesPostRequestBody as QuotesPostRequestBodyMember1);
    serializeQuotesPostRequestBodyMember2(writer, quotesPostRequestBody as QuotesPostRequestBodyMember2);
    serializeQuotesPostRequestBodyMember3(writer, quotesPostRequestBody as QuotesPostRequestBodyMember3);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QuotesPostRequestBodyMember1 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuotesPostRequestBodyMember1(writer: SerializationWriter, quotesPostRequestBodyMember1: Partial<QuotesPostRequestBodyMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!quotesPostRequestBodyMember1 || isSerializingDerivedType) { return; }
    writer.writeEnumValue<PaymentMethod>("method", quotesPostRequestBodyMember1.method);
    writer.writeStringValue("receiver", quotesPostRequestBodyMember1.receiver);
    writer.writeStringValue("walletAddress", quotesPostRequestBodyMember1.walletAddress);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QuotesPostRequestBodyMember2 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuotesPostRequestBodyMember2(writer: SerializationWriter, quotesPostRequestBodyMember2: Partial<QuotesPostRequestBodyMember2> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!quotesPostRequestBodyMember2 || isSerializingDerivedType) { return; }
    writer.writeEnumValue<PaymentMethod>("method", quotesPostRequestBodyMember2.method);
    writer.writeObjectValue<Amount>("receiveAmount", quotesPostRequestBodyMember2.receiveAmount, serializeAmount);
    writer.writeStringValue("receiver", quotesPostRequestBodyMember2.receiver);
    writer.writeStringValue("walletAddress", quotesPostRequestBodyMember2.walletAddress);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param QuotesPostRequestBodyMember3 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuotesPostRequestBodyMember3(writer: SerializationWriter, quotesPostRequestBodyMember3: Partial<QuotesPostRequestBodyMember3> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!quotesPostRequestBodyMember3 || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Amount>("debitAmount", quotesPostRequestBodyMember3.debitAmount, serializeAmount);
    writer.writeEnumValue<PaymentMethod>("method", quotesPostRequestBodyMember3.method);
    writer.writeStringValue("receiver", quotesPostRequestBodyMember3.receiver);
    writer.writeStringValue("walletAddress", quotesPostRequestBodyMember3.walletAddress);
}
/**
 * Uri template for the request builder.
 */
export const QuotesRequestBuilderUriTemplate = "{+baseurl}/quotes";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const QuotesRequestBuilderNavigationMetadata: Record<Exclude<keyof QuotesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: QuotesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const QuotesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QuotesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQuoteFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQuotesPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
