/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, createIncomingPaymentWithMethodsFromDiscriminatorValue, createPublicIncomingPaymentFromDiscriminatorValue, deserializeIntoIncomingPaymentWithMethods, deserializeIntoPublicIncomingPayment, serializeIncomingPaymentWithMethods, serializePublicIncomingPayment, type ErrorResponse, type IncomingPaymentWithMethods, type PublicIncomingPayment } from '../../models/index.js';
// @ts-ignore
import { CompleteRequestBuilderRequestsMetadata, type CompleteRequestBuilder } from './complete/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IncomingPaymentWithMethods | PublicIncomingPayment}
 */
// @ts-ignore
export function createIncomingPaymentsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIncomingPaymentsGetResponse;
}
/**
 * The deserialization information for the current model
 * @param IncomingPaymentsGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIncomingPaymentsGetResponse(incomingPaymentsGetResponse: Partial<IncomingPaymentWithMethods | PublicIncomingPayment> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoIncomingPaymentWithMethods(incomingPaymentsGetResponse as IncomingPaymentWithMethods),
        ...deserializeIntoPublicIncomingPayment(incomingPaymentsGetResponse as PublicIncomingPayment),
    }
}
export type IncomingPaymentsGetResponse = IncomingPaymentWithMethods | PublicIncomingPayment;
/**
 * Builds and executes requests for operations under /incoming-payments/{id}
 */
export interface IncomingPaymentsItemRequestBuilder extends BaseRequestBuilder<IncomingPaymentsItemRequestBuilder> {
    /**
     * The complete property
     */
    get complete(): CompleteRequestBuilder;
    /**
     * A client can fetch the latest state of an incoming payment to determine the amount received into the wallet address.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<IncomingPaymentWithMethods | PublicIncomingPayment>}
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     * @throws {ErrorResponse} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<IncomingPaymentWithMethods | PublicIncomingPayment | undefined>;
    /**
     * A client can fetch the latest state of an incoming payment to determine the amount received into the wallet address.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param IncomingPaymentsGetResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIncomingPaymentsGetResponse(writer: SerializationWriter, incomingPaymentsGetResponse: Partial<IncomingPaymentWithMethods | PublicIncomingPayment> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeIncomingPaymentWithMethods(writer, incomingPaymentsGetResponse as IncomingPaymentWithMethods);
    serializePublicIncomingPayment(writer, incomingPaymentsGetResponse as PublicIncomingPayment);
}
/**
 * Uri template for the request builder.
 */
export const IncomingPaymentsItemRequestBuilderUriTemplate = "{+baseurl}/incoming-payments/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const IncomingPaymentsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof IncomingPaymentsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    complete: {
        requestsMetadata: CompleteRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const IncomingPaymentsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: IncomingPaymentsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createIncomingPaymentsGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
