/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAccess_tokenFromDiscriminatorValue, createErrorInvalidClientFromDiscriminatorValue, createErrorInvalidRotationFromDiscriminatorValue, createErrorRequestDeniedFromDiscriminatorValue, serializeAccess_token, type Access_token, type ErrorInvalidClient, type ErrorInvalidRotation, type ErrorRequestDenied } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TokenPostResponse}
 */
// @ts-ignore
export function createTokenPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTokenPostResponse;
}
/**
 * The deserialization information for the current model
 * @param TokenPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTokenPostResponse(tokenPostResponse: Partial<TokenPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "access_token": n => { tokenPostResponse.accessToken = n.getObjectValue<Access_token>(createAccess_tokenFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TokenPostResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTokenPostResponse(writer: SerializationWriter, tokenPostResponse: Partial<TokenPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!tokenPostResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Access_token>("access_token", tokenPostResponse.accessToken, serializeAccess_token);
    writer.writeAdditionalData(tokenPostResponse.additionalData);
}
/**
 * Builds and executes requests for operations under /token/{id}
 */
export interface TokenItemRequestBuilder extends BaseRequestBuilder<TokenItemRequestBuilder> {
    /**
     * Management endpoint to revoke access token.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ErrorInvalidClient} error when the service returns a 401 status code
     * @throws {ErrorRequestDenied} error when the service returns a 500 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Management endpoint to rotate access token.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TokenPostResponse>}
     * @throws {ErrorInvalidRotation} error when the service returns a 400 status code
     * @throws {ErrorInvalidClient} error when the service returns a 401 status code
     * @throws {ErrorInvalidRotation} error when the service returns a 404 status code
     * @throws {ErrorRequestDenied} error when the service returns a 500 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TokenPostResponse | undefined>;
    /**
     * Management endpoint to revoke access token.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Management endpoint to rotate access token.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface TokenPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * A single access token or set of access tokens that the client instance can use to call the RS on behalf of the RO.
     */
    accessToken?: Access_token | null;
}
/**
 * Uri template for the request builder.
 */
export const TokenItemRequestBuilderUriTemplate = "{+baseurl}/token/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const TokenItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: TokenItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorInvalidClientFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorRequestDeniedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    post: {
        uriTemplate: TokenItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorInvalidRotationFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorInvalidClientFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorInvalidRotationFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorRequestDeniedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTokenPostResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
