/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAmountFromDiscriminatorValue, createErrorResponseFromDiscriminatorValue, createOutgoingPaymentFromDiscriminatorValue, createOutgoingPaymentWithSpentAmountsFromDiscriminatorValue, createPageInfoFromDiscriminatorValue, serializeAmount, serializeOutgoingPayment, serializeOutgoingPaymentWithSpentAmounts, serializePageInfo, type Amount, type ErrorResponse, type OutgoingPayment, type OutgoingPaymentWithSpentAmounts, type PageInfo } from '../models/index.js';
// @ts-ignore
import { OutgoingPaymentsItemRequestBuilderRequestsMetadata, type OutgoingPaymentsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OutgoingPaymentsGetResponse}
 */
// @ts-ignore
export function createOutgoingPaymentsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOutgoingPaymentsGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OutgoingPaymentsPostRequestBodyMember1 | OutgoingPaymentsPostRequestBodyMember2}
 */
// @ts-ignore
export function createOutgoingPaymentsPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOutgoingPaymentsPostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OutgoingPaymentsPostRequestBodyMember1_metadata}
 */
// @ts-ignore
export function createOutgoingPaymentsPostRequestBodyMember1_metadataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOutgoingPaymentsPostRequestBodyMember1_metadata;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OutgoingPaymentsPostRequestBodyMember1}
 */
// @ts-ignore
export function createOutgoingPaymentsPostRequestBodyMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOutgoingPaymentsPostRequestBodyMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OutgoingPaymentsPostRequestBodyMember2_metadata}
 */
// @ts-ignore
export function createOutgoingPaymentsPostRequestBodyMember2_metadataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOutgoingPaymentsPostRequestBodyMember2_metadata;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OutgoingPaymentsPostRequestBodyMember2}
 */
// @ts-ignore
export function createOutgoingPaymentsPostRequestBodyMember2FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOutgoingPaymentsPostRequestBodyMember2;
}
/**
 * The deserialization information for the current model
 * @param OutgoingPaymentsGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOutgoingPaymentsGetResponse(outgoingPaymentsGetResponse: Partial<OutgoingPaymentsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "pagination": n => { outgoingPaymentsGetResponse.pagination = n.getObjectValue<PageInfo>(createPageInfoFromDiscriminatorValue); },
        "result": n => { outgoingPaymentsGetResponse.result = n.getCollectionOfObjectValues<OutgoingPayment>(createOutgoingPaymentFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param OutgoingPaymentsPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOutgoingPaymentsPostRequestBody(outgoingPaymentsPostRequestBody: Partial<OutgoingPaymentsPostRequestBodyMember1 | OutgoingPaymentsPostRequestBodyMember2> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoOutgoingPaymentsPostRequestBodyMember1(outgoingPaymentsPostRequestBody as OutgoingPaymentsPostRequestBodyMember1),
        ...deserializeIntoOutgoingPaymentsPostRequestBodyMember2(outgoingPaymentsPostRequestBody as OutgoingPaymentsPostRequestBodyMember2),
    }
}
/**
 * The deserialization information for the current model
 * @param OutgoingPaymentsPostRequestBodyMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOutgoingPaymentsPostRequestBodyMember1(outgoingPaymentsPostRequestBodyMember1: Partial<OutgoingPaymentsPostRequestBodyMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "metadata": n => { outgoingPaymentsPostRequestBodyMember1.metadata = n.getObjectValue<OutgoingPaymentsPostRequestBodyMember1_metadata>(createOutgoingPaymentsPostRequestBodyMember1_metadataFromDiscriminatorValue); },
        "quoteId": n => { outgoingPaymentsPostRequestBodyMember1.quoteId = n.getStringValue(); },
        "walletAddress": n => { outgoingPaymentsPostRequestBodyMember1.walletAddress = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param OutgoingPaymentsPostRequestBodyMember1_metadata The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOutgoingPaymentsPostRequestBodyMember1_metadata(outgoingPaymentsPostRequestBodyMember1_metadata: Partial<OutgoingPaymentsPostRequestBodyMember1_metadata> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param OutgoingPaymentsPostRequestBodyMember2 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOutgoingPaymentsPostRequestBodyMember2(outgoingPaymentsPostRequestBodyMember2: Partial<OutgoingPaymentsPostRequestBodyMember2> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "debitAmount": n => { outgoingPaymentsPostRequestBodyMember2.debitAmount = n.getObjectValue<Amount>(createAmountFromDiscriminatorValue); },
        "incomingPayment": n => { outgoingPaymentsPostRequestBodyMember2.incomingPayment = n.getStringValue(); },
        "metadata": n => { outgoingPaymentsPostRequestBodyMember2.metadata = n.getObjectValue<OutgoingPaymentsPostRequestBodyMember2_metadata>(createOutgoingPaymentsPostRequestBodyMember2_metadataFromDiscriminatorValue); },
        "walletAddress": n => { outgoingPaymentsPostRequestBodyMember2.walletAddress = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param OutgoingPaymentsPostRequestBodyMember2_metadata The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOutgoingPaymentsPostRequestBodyMember2_metadata(outgoingPaymentsPostRequestBodyMember2_metadata: Partial<OutgoingPaymentsPostRequestBodyMember2_metadata> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
export interface OutgoingPaymentsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * The pagination property
     */
    pagination?: PageInfo | null;
    /**
     * The result property
     */
    result?: OutgoingPayment[] | null;
}
export type OutgoingPaymentsPostRequestBody = OutgoingPaymentsPostRequestBodyMember1 | OutgoingPaymentsPostRequestBodyMember2;
export interface OutgoingPaymentsPostRequestBodyMember1 extends Parsable {
    /**
     * Additional metadata associated with the outgoing payment. (Optional)
     */
    metadata?: OutgoingPaymentsPostRequestBodyMember1_metadata | null;
    /**
     * The URL of the quote defining this payment's amounts.
     */
    quoteId?: string | null;
    /**
     * The URL of an Open Payments wallet address
     */
    walletAddress?: string | null;
}
/**
 * Additional metadata associated with the outgoing payment. (Optional)
 */
export interface OutgoingPaymentsPostRequestBodyMember1_metadata extends AdditionalDataHolder, Parsable {
}
export interface OutgoingPaymentsPostRequestBodyMember2 extends Parsable {
    /**
     * The fixed amount that would be sent from the sending wallet address given a successful outgoing payment.
     */
    debitAmount?: Amount | null;
    /**
     * The URL of the incoming payment this outgoing payment will fulfill.
     */
    incomingPayment?: string | null;
    /**
     * Additional metadata associated with the outgoing payment. (Optional)
     */
    metadata?: OutgoingPaymentsPostRequestBodyMember2_metadata | null;
    /**
     * The URL of an Open Payments wallet address
     */
    walletAddress?: string | null;
}
/**
 * Additional metadata associated with the outgoing payment. (Optional)
 */
export interface OutgoingPaymentsPostRequestBodyMember2_metadata extends AdditionalDataHolder, Parsable {
}
/**
 * Create a new outgoing payment at the wallet address.
 */
export interface OutgoingPaymentsRequestBuilder extends BaseRequestBuilder<OutgoingPaymentsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.outgoingPayments.item collection
     * @param id Sub-resource identifier
     * @returns {OutgoingPaymentsItemRequestBuilder}
     */
     byId(id: string) : OutgoingPaymentsItemRequestBuilder;
    /**
     * List all outgoing payments on the wallet address
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OutgoingPaymentsGetResponse>}
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     */
     get(requestConfiguration?: RequestConfiguration<OutgoingPaymentsRequestBuilderGetQueryParameters> | undefined) : Promise<OutgoingPaymentsGetResponse | undefined>;
    /**
     * An **outgoing payment** is a sub-resource of a wallet address. It represents a payment from the wallet address.Once created, it is already authorized and SHOULD be processed immediately. If payment fails, the Account Servicing Entity must mark the **outgoing payment** as `failed`.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OutgoingPaymentWithSpentAmounts>}
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     */
     post(body: OutgoingPaymentsPostRequestBodyMember1 | OutgoingPaymentsPostRequestBodyMember2, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<OutgoingPaymentWithSpentAmounts | undefined>;
    /**
     * List all outgoing payments on the wallet address
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<OutgoingPaymentsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * An **outgoing payment** is a sub-resource of a wallet address. It represents a payment from the wallet address.Once created, it is already authorized and SHOULD be processed immediately. If payment fails, the Account Servicing Entity must mark the **outgoing payment** as `failed`.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: OutgoingPaymentsPostRequestBodyMember1 | OutgoingPaymentsPostRequestBodyMember2, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * List all outgoing payments on the wallet address
 */
export interface OutgoingPaymentsRequestBuilderGetQueryParameters {
    /**
     * The cursor key to list from.
     */
    cursor?: string;
    /**
     * The number of items to return after the cursor.
     */
    first?: number;
    /**
     * The number of items to return before the cursor.
     */
    last?: number;
    /**
     * URL of a wallet address hosted by a Rafiki instance.
     */
    walletAddress?: string;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OutgoingPaymentsGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOutgoingPaymentsGetResponse(writer: SerializationWriter, outgoingPaymentsGetResponse: Partial<OutgoingPaymentsGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!outgoingPaymentsGetResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<PageInfo>("pagination", outgoingPaymentsGetResponse.pagination, serializePageInfo);
    writer.writeCollectionOfObjectValues<OutgoingPayment>("result", outgoingPaymentsGetResponse.result, serializeOutgoingPayment);
    writer.writeAdditionalData(outgoingPaymentsGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OutgoingPaymentsPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOutgoingPaymentsPostRequestBody(writer: SerializationWriter, outgoingPaymentsPostRequestBody: Partial<OutgoingPaymentsPostRequestBodyMember1 | OutgoingPaymentsPostRequestBodyMember2> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeOutgoingPaymentsPostRequestBodyMember1(writer, outgoingPaymentsPostRequestBody as OutgoingPaymentsPostRequestBodyMember1);
    serializeOutgoingPaymentsPostRequestBodyMember2(writer, outgoingPaymentsPostRequestBody as OutgoingPaymentsPostRequestBodyMember2);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OutgoingPaymentsPostRequestBodyMember1 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOutgoingPaymentsPostRequestBodyMember1(writer: SerializationWriter, outgoingPaymentsPostRequestBodyMember1: Partial<OutgoingPaymentsPostRequestBodyMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!outgoingPaymentsPostRequestBodyMember1 || isSerializingDerivedType) { return; }
    writer.writeObjectValue<OutgoingPaymentsPostRequestBodyMember1_metadata>("metadata", outgoingPaymentsPostRequestBodyMember1.metadata, serializeOutgoingPaymentsPostRequestBodyMember1_metadata);
    writer.writeStringValue("quoteId", outgoingPaymentsPostRequestBodyMember1.quoteId);
    writer.writeStringValue("walletAddress", outgoingPaymentsPostRequestBodyMember1.walletAddress);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OutgoingPaymentsPostRequestBodyMember1_metadata The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOutgoingPaymentsPostRequestBodyMember1_metadata(writer: SerializationWriter, outgoingPaymentsPostRequestBodyMember1_metadata: Partial<OutgoingPaymentsPostRequestBodyMember1_metadata> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!outgoingPaymentsPostRequestBodyMember1_metadata || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(outgoingPaymentsPostRequestBodyMember1_metadata.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OutgoingPaymentsPostRequestBodyMember2 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOutgoingPaymentsPostRequestBodyMember2(writer: SerializationWriter, outgoingPaymentsPostRequestBodyMember2: Partial<OutgoingPaymentsPostRequestBodyMember2> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!outgoingPaymentsPostRequestBodyMember2 || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Amount>("debitAmount", outgoingPaymentsPostRequestBodyMember2.debitAmount, serializeAmount);
    writer.writeStringValue("incomingPayment", outgoingPaymentsPostRequestBodyMember2.incomingPayment);
    writer.writeObjectValue<OutgoingPaymentsPostRequestBodyMember2_metadata>("metadata", outgoingPaymentsPostRequestBodyMember2.metadata, serializeOutgoingPaymentsPostRequestBodyMember2_metadata);
    writer.writeStringValue("walletAddress", outgoingPaymentsPostRequestBodyMember2.walletAddress);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param OutgoingPaymentsPostRequestBodyMember2_metadata The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOutgoingPaymentsPostRequestBodyMember2_metadata(writer: SerializationWriter, outgoingPaymentsPostRequestBodyMember2_metadata: Partial<OutgoingPaymentsPostRequestBodyMember2_metadata> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!outgoingPaymentsPostRequestBodyMember2_metadata || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(outgoingPaymentsPostRequestBodyMember2_metadata.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const OutgoingPaymentsRequestBuilderUriTemplate = "{+baseurl}/outgoing-payments?wallet-address={wallet%2Daddress}{&cursor*,first*,last*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const OutgoingPaymentsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "walletAddress": "wallet%2Daddress",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OutgoingPaymentsRequestBuilderNavigationMetadata: Record<Exclude<keyof OutgoingPaymentsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: OutgoingPaymentsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const OutgoingPaymentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OutgoingPaymentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOutgoingPaymentsGetResponseFromDiscriminatorValue,
        queryParametersMapper: OutgoingPaymentsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: OutgoingPaymentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOutgoingPaymentWithSpentAmountsFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeOutgoingPaymentsPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
