/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * A single access token or set of access tokens that the client instance can use to call the RS on behalf of the RO.
 */
export interface Access_token extends Parsable {
    /**
     * A description of the rights associated with this access token.
     */
    access?: (AccessIncoming | AccessOutgoing | AccessQuote)[] | null;
    /**
     * The number of seconds in which the access will expire.  The client instance MUST NOT use the access token past this time.  An RS MUST NOT accept an access token past this time.
     */
    expiresIn?: number | null;
    /**
     * The management URI for this access token. This URI MUST NOT include the access token value and SHOULD be different for each access token issued in a request.
     */
    manage?: string | null;
    /**
     * The value of the access token as a string.  The value is opaque to the client instance.  The value SHOULD be limited to ASCII characters to facilitate transmission over HTTP headers within other protocols without requiring additional encoding.
     */
    value?: string | null;
}
export interface AccessIncoming extends AdditionalDataHolder, Parsable {
    /**
     * The types of actions the client instance will take at the RS as an array of strings.
     */
    actions?: AccessIncoming_actions[] | null;
    /**
     * A string identifier indicating a specific resource at the RS.
     */
    identifier?: string | null;
    /**
     * The type of resource request as a string.  This field defines which other fields are allowed in the request object.
     */
    type?: AccessIncoming_type | null;
}
export type AccessIncoming_actions = (typeof AccessIncoming_actionsObject)[keyof typeof AccessIncoming_actionsObject];
export type AccessIncoming_type = (typeof AccessIncoming_typeObject)[keyof typeof AccessIncoming_typeObject];
export type AccessItem = AccessIncoming | AccessOutgoing | AccessQuote;
export interface AccessOutgoing extends AdditionalDataHolder, Parsable {
    /**
     * The types of actions the client instance will take at the RS as an array of strings.
     */
    actions?: AccessOutgoing_actions[] | null;
    /**
     * A string identifier indicating a specific resource at the RS.
     */
    identifier?: string | null;
    /**
     * Open Payments specific property that defines the limits under which outgoing payments can be created.
     */
    limits?: LimitsOutgoingMember1 | LimitsOutgoingMember2 | LimitsOutgoingMember3 | null;
    /**
     * The type of resource request as a string.  This field defines which other fields are allowed in the request object.
     */
    type?: AccessOutgoing_type | null;
}
export type AccessOutgoing_actions = (typeof AccessOutgoing_actionsObject)[keyof typeof AccessOutgoing_actionsObject];
export type AccessOutgoing_type = (typeof AccessOutgoing_typeObject)[keyof typeof AccessOutgoing_typeObject];
export interface AccessQuote extends AdditionalDataHolder, Parsable {
    /**
     * The types of actions the client instance will take at the RS as an array of strings.
     */
    actions?: AccessQuote_actions[] | null;
    /**
     * The type of resource request as a string.  This field defines which other fields are allowed in the request object.
     */
    type?: AccessQuote_type | null;
}
export type AccessQuote_actions = (typeof AccessQuote_actionsObject)[keyof typeof AccessQuote_actionsObject];
export type AccessQuote_type = (typeof AccessQuote_typeObject)[keyof typeof AccessQuote_typeObject];
/**
 * All amounts are maxima, i.e. multiple payments can be created under a grant as long as the total amounts of these payments do not exceed the maximum amount per interval as specified in the grant.
 */
export interface Amount extends AdditionalDataHolder, Parsable {
    /**
     * The assetCode is a code that indicates the underlying asset. An ISO4217 currency code should be used whenever possible. The ISO4217 representation of the US Dollar is USD.
     */
    assetCode?: string | null;
    /**
     * The number of decimal places that defines the scale of the smallest divisible unit for the given asset code. It determines how an integer amount is scaled to derive the actual monetary value. For example, USD has an asset scale of 2 with the smallest unit being 0.01. An integer amount of `1000` with an `assetCode` of `USD` and `assetScale` of `2` translates to $10.00.
     */
    assetScale?: number | null;
    /**
     * The value is an unsigned 64-bit integer amount, represented as a string.
     */
    value?: string | null;
}
/**
 * A unique access token for continuing the request, called the "continuation access token".
 */
export interface Continue_access_token extends AdditionalDataHolder, Parsable {
    /**
     * The value property
     */
    value?: string | null;
}
/**
 * If the AS determines that the request can be continued with additional requests, it responds with the continue field.
 */
export interface ContinueEscaped extends AdditionalDataHolder, Parsable {
    /**
     * A unique access token for continuing the request, called the "continuation access token".
     */
    accessToken?: Continue_access_token | null;
    /**
     * The URI at which the client instance can make continuation requests.
     */
    uri?: string | null;
    /**
     * The amount of time in integer seconds the client instance MUST wait after receiving this request continuation response and calling the continuation URI.
     */
    wait?: number | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Access_token}
 */
// @ts-ignore
export function createAccess_tokenFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccess_token;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AccessIncoming}
 */
// @ts-ignore
export function createAccessIncomingFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccessIncoming;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AccessIncoming | AccessOutgoing | AccessQuote}
 */
// @ts-ignore
export function createAccessItemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccessItem;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AccessOutgoing}
 */
// @ts-ignore
export function createAccessOutgoingFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccessOutgoing;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AccessQuote}
 */
// @ts-ignore
export function createAccessQuoteFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAccessQuote;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Amount}
 */
// @ts-ignore
export function createAmountFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAmount;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Continue_access_token}
 */
// @ts-ignore
export function createContinue_access_tokenFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoContinue_access_token;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ContinueEscaped}
 */
// @ts-ignore
export function createContinueEscapedFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoContinueEscaped;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorInvalidClient_error}
 */
// @ts-ignore
export function createErrorInvalidClient_errorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorInvalidClient_error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorInvalidClient}
 */
// @ts-ignore
export function createErrorInvalidClientFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorInvalidClient;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorInvalidRequest_error}
 */
// @ts-ignore
export function createErrorInvalidRequest_errorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorInvalidRequest_error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorInvalidRequest}
 */
// @ts-ignore
export function createErrorInvalidRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorInvalidRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorInvalidRotation_error}
 */
// @ts-ignore
export function createErrorInvalidRotation_errorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorInvalidRotation_error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorInvalidRotation}
 */
// @ts-ignore
export function createErrorInvalidRotationFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorInvalidRotation;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorRequestDenied_error}
 */
// @ts-ignore
export function createErrorRequestDenied_errorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorRequestDenied_error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorRequestDenied}
 */
// @ts-ignore
export function createErrorRequestDeniedFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorRequestDenied;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InteractRequest_finish}
 */
// @ts-ignore
export function createInteractRequest_finishFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInteractRequest_finish;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InteractRequest}
 */
// @ts-ignore
export function createInteractRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInteractRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InteractResponse}
 */
// @ts-ignore
export function createInteractResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInteractResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LimitsOutgoingMember1 | LimitsOutgoingMember2 | LimitsOutgoingMember3}
 */
// @ts-ignore
export function createLimitsOutgoingFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLimitsOutgoing;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LimitsOutgoingMember1}
 */
// @ts-ignore
export function createLimitsOutgoingMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLimitsOutgoingMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LimitsOutgoingMember2}
 */
// @ts-ignore
export function createLimitsOutgoingMember2FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLimitsOutgoingMember2;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LimitsOutgoingMember3}
 */
// @ts-ignore
export function createLimitsOutgoingMember3FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLimitsOutgoingMember3;
}
/**
 * The deserialization information for the current model
 * @param Access_token The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccess_token(access_token: Partial<Access_token> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "access": n => { access_token.access = n.getCollectionOfObjectValues<AccessIncoming>(createAccessIncomingFromDiscriminatorValue) ?? n.getCollectionOfObjectValues<AccessOutgoing>(createAccessOutgoingFromDiscriminatorValue) ?? n.getCollectionOfObjectValues<AccessQuote>(createAccessQuoteFromDiscriminatorValue); },
        "expires_in": n => { access_token.expiresIn = n.getNumberValue(); },
        "manage": n => { access_token.manage = n.getStringValue(); },
        "value": n => { access_token.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AccessIncoming The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccessIncoming(accessIncoming: Partial<AccessIncoming> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "actions": n => { accessIncoming.actions = n.getCollectionOfEnumValues<AccessIncoming_actions>(AccessIncoming_actionsObject); },
        "identifier": n => { accessIncoming.identifier = n.getStringValue(); },
        "type": n => { accessIncoming.type = n.getEnumValue<AccessIncoming_type>(AccessIncoming_typeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param AccessItem The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccessItem(accessItem: Partial<AccessIncoming | AccessOutgoing | AccessQuote> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoAccessIncoming(accessItem as AccessIncoming),
        ...deserializeIntoAccessOutgoing(accessItem as AccessOutgoing),
        ...deserializeIntoAccessQuote(accessItem as AccessQuote),
    }
}
/**
 * The deserialization information for the current model
 * @param AccessOutgoing The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccessOutgoing(accessOutgoing: Partial<AccessOutgoing> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "actions": n => { accessOutgoing.actions = n.getCollectionOfEnumValues<AccessOutgoing_actions>(AccessOutgoing_actionsObject); },
        "identifier": n => { accessOutgoing.identifier = n.getStringValue(); },
        "limits": n => { accessOutgoing.limits = n.getObjectValue<LimitsOutgoingMember1>(createLimitsOutgoingMember1FromDiscriminatorValue) ?? n.getObjectValue<LimitsOutgoingMember2>(createLimitsOutgoingMember2FromDiscriminatorValue) ?? n.getObjectValue<LimitsOutgoingMember3>(createLimitsOutgoingMember3FromDiscriminatorValue); },
        "type": n => { accessOutgoing.type = n.getEnumValue<AccessOutgoing_type>(AccessOutgoing_typeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param AccessQuote The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAccessQuote(accessQuote: Partial<AccessQuote> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "actions": n => { accessQuote.actions = n.getCollectionOfEnumValues<AccessQuote_actions>(AccessQuote_actionsObject); },
        "type": n => { accessQuote.type = n.getEnumValue<AccessQuote_type>(AccessQuote_typeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param Amount The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAmount(amount: Partial<Amount> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "assetCode": n => { amount.assetCode = n.getStringValue(); },
        "assetScale": n => { amount.assetScale = n.getNumberValue(); },
        "value": n => { amount.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Continue_access_token The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoContinue_access_token(continue_access_token: Partial<Continue_access_token> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { continue_access_token.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ContinueEscaped The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoContinueEscaped(continueEscaped: Partial<ContinueEscaped> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "access_token": n => { continueEscaped.accessToken = n.getObjectValue<Continue_access_token>(createContinue_access_tokenFromDiscriminatorValue); },
        "uri": n => { continueEscaped.uri = n.getStringValue(); },
        "wait": n => { continueEscaped.wait = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorInvalidClient The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorInvalidClient(errorInvalidClient: Partial<ErrorInvalidClient> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "error": n => { errorInvalidClient.errorEscaped = n.getObjectValue<ErrorInvalidClient_error>(createErrorInvalidClient_errorFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorInvalidClient_error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorInvalidClient_error(errorInvalidClient_error: Partial<ErrorInvalidClient_error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { errorInvalidClient_error.code = n.getEnumValue<ErrorInvalidClient_error_code>(ErrorInvalidClient_error_codeObject); },
        "description": n => { errorInvalidClient_error.description = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorInvalidRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorInvalidRequest(errorInvalidRequest: Partial<ErrorInvalidRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "error": n => { errorInvalidRequest.errorEscaped = n.getObjectValue<ErrorInvalidRequest_error>(createErrorInvalidRequest_errorFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorInvalidRequest_error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorInvalidRequest_error(errorInvalidRequest_error: Partial<ErrorInvalidRequest_error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { errorInvalidRequest_error.code = n.getEnumValue<ErrorInvalidRequest_error_code>(ErrorInvalidRequest_error_codeObject); },
        "description": n => { errorInvalidRequest_error.description = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorInvalidRotation The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorInvalidRotation(errorInvalidRotation: Partial<ErrorInvalidRotation> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "error": n => { errorInvalidRotation.errorEscaped = n.getObjectValue<ErrorInvalidRotation_error>(createErrorInvalidRotation_errorFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorInvalidRotation_error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorInvalidRotation_error(errorInvalidRotation_error: Partial<ErrorInvalidRotation_error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { errorInvalidRotation_error.code = n.getEnumValue<ErrorInvalidRotation_error_code>(ErrorInvalidRotation_error_codeObject); },
        "description": n => { errorInvalidRotation_error.description = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorRequestDenied The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorRequestDenied(errorRequestDenied: Partial<ErrorRequestDenied> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "error": n => { errorRequestDenied.errorEscaped = n.getObjectValue<ErrorRequestDenied_error>(createErrorRequestDenied_errorFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorRequestDenied_error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorRequestDenied_error(errorRequestDenied_error: Partial<ErrorRequestDenied_error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { errorRequestDenied_error.code = n.getEnumValue<ErrorRequestDenied_error_code>(ErrorRequestDenied_error_codeObject); },
        "description": n => { errorRequestDenied_error.description = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param InteractRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInteractRequest(interactRequest: Partial<InteractRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "finish": n => { interactRequest.finish = n.getObjectValue<InteractRequest_finish>(createInteractRequest_finishFromDiscriminatorValue); },
        "start": n => { interactRequest.start = n.getCollectionOfEnumValues<InteractRequest_start>(InteractRequest_startObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param InteractRequest_finish The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInteractRequest_finish(interactRequest_finish: Partial<InteractRequest_finish> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "method": n => { interactRequest_finish.method = n.getEnumValue<InteractRequest_finish_method>(InteractRequest_finish_methodObject); },
        "nonce": n => { interactRequest_finish.nonce = n.getStringValue(); },
        "uri": n => { interactRequest_finish.uri = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param InteractResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInteractResponse(interactResponse: Partial<InteractResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "finish": n => { interactResponse.finish = n.getStringValue(); },
        "redirect": n => { interactResponse.redirect = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LimitsOutgoing The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLimitsOutgoing(limitsOutgoing: Partial<LimitsOutgoingMember1 | LimitsOutgoingMember2 | LimitsOutgoingMember3> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoLimitsOutgoingMember1(limitsOutgoing as LimitsOutgoingMember1),
        ...deserializeIntoLimitsOutgoingMember2(limitsOutgoing as LimitsOutgoingMember2),
        ...deserializeIntoLimitsOutgoingMember3(limitsOutgoing as LimitsOutgoingMember3),
    }
}
/**
 * The deserialization information for the current model
 * @param LimitsOutgoingMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLimitsOutgoingMember1(limitsOutgoingMember1: Partial<LimitsOutgoingMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "interval": n => { limitsOutgoingMember1.interval = n.getStringValue(); },
        "receiver": n => { limitsOutgoingMember1.receiver = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LimitsOutgoingMember2 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLimitsOutgoingMember2(limitsOutgoingMember2: Partial<LimitsOutgoingMember2> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "debitAmount": n => { limitsOutgoingMember2.debitAmount = n.getObjectValue<Amount>(createAmountFromDiscriminatorValue); },
        "interval": n => { limitsOutgoingMember2.interval = n.getStringValue(); },
        "receiver": n => { limitsOutgoingMember2.receiver = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LimitsOutgoingMember3 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLimitsOutgoingMember3(limitsOutgoingMember3: Partial<LimitsOutgoingMember3> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "interval": n => { limitsOutgoingMember3.interval = n.getStringValue(); },
        "receiveAmount": n => { limitsOutgoingMember3.receiveAmount = n.getObjectValue<Amount>(createAmountFromDiscriminatorValue); },
        "receiver": n => { limitsOutgoingMember3.receiver = n.getStringValue(); },
    }
}
export interface ErrorInvalidClient extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The error property
     */
    errorEscaped?: ErrorInvalidClient_error | null;
}
export interface ErrorInvalidClient_error extends AdditionalDataHolder, Parsable {
    /**
     * The code property
     */
    code?: ErrorInvalidClient_error_code | null;
    /**
     * The description property
     */
    description?: string | null;
}
export type ErrorInvalidClient_error_code = (typeof ErrorInvalidClient_error_codeObject)[keyof typeof ErrorInvalidClient_error_codeObject];
export interface ErrorInvalidRequest extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The error property
     */
    errorEscaped?: ErrorInvalidRequest_error | null;
}
export interface ErrorInvalidRequest_error extends AdditionalDataHolder, Parsable {
    /**
     * The code property
     */
    code?: ErrorInvalidRequest_error_code | null;
    /**
     * The description property
     */
    description?: string | null;
}
export type ErrorInvalidRequest_error_code = (typeof ErrorInvalidRequest_error_codeObject)[keyof typeof ErrorInvalidRequest_error_codeObject];
export interface ErrorInvalidRotation extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The error property
     */
    errorEscaped?: ErrorInvalidRotation_error | null;
}
export interface ErrorInvalidRotation_error extends AdditionalDataHolder, Parsable {
    /**
     * The code property
     */
    code?: ErrorInvalidRotation_error_code | null;
    /**
     * The description property
     */
    description?: string | null;
}
export type ErrorInvalidRotation_error_code = (typeof ErrorInvalidRotation_error_codeObject)[keyof typeof ErrorInvalidRotation_error_codeObject];
export interface ErrorRequestDenied extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The error property
     */
    errorEscaped?: ErrorRequestDenied_error | null;
}
export interface ErrorRequestDenied_error extends AdditionalDataHolder, Parsable {
    /**
     * The code property
     */
    code?: ErrorRequestDenied_error_code | null;
    /**
     * The description property
     */
    description?: string | null;
}
export type ErrorRequestDenied_error_code = (typeof ErrorRequestDenied_error_codeObject)[keyof typeof ErrorRequestDenied_error_codeObject];
/**
 * The client instance declares the parameters for interaction methods that it can support using the interact field.
 */
export interface InteractRequest extends AdditionalDataHolder, Parsable {
    /**
     * Indicates how the client instance can receive an indication that interaction has finished at the AS.
     */
    finish?: InteractRequest_finish | null;
    /**
     * Indicates how the client instance can start an interaction.
     */
    start?: InteractRequest_start[] | null;
}
/**
 * Indicates how the client instance can receive an indication that interaction has finished at the AS.
 */
export interface InteractRequest_finish extends AdditionalDataHolder, Parsable {
    /**
     * The callback method that the AS will use to contact the client instance.
     */
    method?: InteractRequest_finish_method | null;
    /**
     * Unique value to be used in the calculation of the "hash" query parameter sent to the callback URI, must be sufficiently random to be unguessable by an attacker.  MUST be generated by the client instance as a unique value for this request.
     */
    nonce?: string | null;
    /**
     * Indicates the URI that the AS will either send the RO to after interaction or send an HTTP POST request.
     */
    uri?: string | null;
}
export type InteractRequest_finish_method = (typeof InteractRequest_finish_methodObject)[keyof typeof InteractRequest_finish_methodObject];
export type InteractRequest_start = (typeof InteractRequest_startObject)[keyof typeof InteractRequest_startObject];
export interface InteractResponse extends AdditionalDataHolder, Parsable {
    /**
     * Unique key to secure the callback.
     */
    finish?: string | null;
    /**
     * The URI to direct the end user to.
     */
    redirect?: string | null;
}
export type LimitsOutgoing = LimitsOutgoingMember1 | LimitsOutgoingMember2 | LimitsOutgoingMember3;
export interface LimitsOutgoingMember1 extends AdditionalDataHolder, Parsable {
    /**
     * [ISO8601 repeating interval](https://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals)
     */
    interval?: string | null;
    /**
     * The URL of the incoming payment that is being paid.
     */
    receiver?: string | null;
}
export interface LimitsOutgoingMember2 extends AdditionalDataHolder, Parsable {
    /**
     * All amounts are maxima, i.e. multiple payments can be created under a grant as long as the total amounts of these payments do not exceed the maximum amount per interval as specified in the grant.
     */
    debitAmount?: Amount | null;
    /**
     * [ISO8601 repeating interval](https://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals)
     */
    interval?: string | null;
    /**
     * The URL of the incoming payment that is being paid.
     */
    receiver?: string | null;
}
export interface LimitsOutgoingMember3 extends AdditionalDataHolder, Parsable {
    /**
     * [ISO8601 repeating interval](https://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals)
     */
    interval?: string | null;
    /**
     * All amounts are maxima, i.e. multiple payments can be created under a grant as long as the total amounts of these payments do not exceed the maximum amount per interval as specified in the grant.
     */
    receiveAmount?: Amount | null;
    /**
     * The URL of the incoming payment that is being paid.
     */
    receiver?: string | null;
}
/**
 * Serializes information the current object
 * @param Access_token The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccess_token(writer: SerializationWriter, access_token: Partial<Access_token> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!access_token || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<AccessIncoming | AccessOutgoing | AccessQuote>("access", access_token.access, serializeAccessItem);
    writer.writeNumberValue("expires_in", access_token.expiresIn);
    writer.writeStringValue("manage", access_token.manage);
    writer.writeStringValue("value", access_token.value);
}
/**
 * Serializes information the current object
 * @param AccessIncoming The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccessIncoming(writer: SerializationWriter, accessIncoming: Partial<AccessIncoming> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!accessIncoming || isSerializingDerivedType) { return; }
    if(accessIncoming.actions)
    writer.writeCollectionOfEnumValues<AccessIncoming_actions>("actions", accessIncoming.actions);
    writer.writeStringValue("identifier", accessIncoming.identifier);
    writer.writeEnumValue<AccessIncoming_type>("type", accessIncoming.type);
    writer.writeAdditionalData(accessIncoming.additionalData);
}
/**
 * Serializes information the current object
 * @param AccessItem The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccessItem(writer: SerializationWriter, accessItem: Partial<AccessIncoming | AccessOutgoing | AccessQuote> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeAccessIncoming(writer, accessItem as AccessIncoming);
    serializeAccessOutgoing(writer, accessItem as AccessOutgoing);
    serializeAccessQuote(writer, accessItem as AccessQuote);
}
/**
 * Serializes information the current object
 * @param AccessOutgoing The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccessOutgoing(writer: SerializationWriter, accessOutgoing: Partial<AccessOutgoing> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!accessOutgoing || isSerializingDerivedType) { return; }
    if(accessOutgoing.actions)
    writer.writeCollectionOfEnumValues<AccessOutgoing_actions>("actions", accessOutgoing.actions);
    writer.writeStringValue("identifier", accessOutgoing.identifier);
    writer.writeObjectValue<LimitsOutgoingMember1 | LimitsOutgoingMember2 | LimitsOutgoingMember3>("limits", accessOutgoing.limits, serializeLimitsOutgoing);
    writer.writeEnumValue<AccessOutgoing_type>("type", accessOutgoing.type);
    writer.writeAdditionalData(accessOutgoing.additionalData);
}
/**
 * Serializes information the current object
 * @param AccessQuote The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAccessQuote(writer: SerializationWriter, accessQuote: Partial<AccessQuote> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!accessQuote || isSerializingDerivedType) { return; }
    if(accessQuote.actions)
    writer.writeCollectionOfEnumValues<AccessQuote_actions>("actions", accessQuote.actions);
    writer.writeEnumValue<AccessQuote_type>("type", accessQuote.type);
    writer.writeAdditionalData(accessQuote.additionalData);
}
/**
 * Serializes information the current object
 * @param Amount The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAmount(writer: SerializationWriter, amount: Partial<Amount> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!amount || isSerializingDerivedType) { return; }
    writer.writeStringValue("assetCode", amount.assetCode);
    writer.writeNumberValue("assetScale", amount.assetScale);
    writer.writeStringValue("value", amount.value);
    writer.writeAdditionalData(amount.additionalData);
}
/**
 * Serializes information the current object
 * @param Continue_access_token The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeContinue_access_token(writer: SerializationWriter, continue_access_token: Partial<Continue_access_token> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!continue_access_token || isSerializingDerivedType) { return; }
    writer.writeStringValue("value", continue_access_token.value);
    writer.writeAdditionalData(continue_access_token.additionalData);
}
/**
 * Serializes information the current object
 * @param ContinueEscaped The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeContinueEscaped(writer: SerializationWriter, continueEscaped: Partial<ContinueEscaped> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!continueEscaped || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Continue_access_token>("access_token", continueEscaped.accessToken, serializeContinue_access_token);
    writer.writeStringValue("uri", continueEscaped.uri);
    writer.writeNumberValue("wait", continueEscaped.wait);
    writer.writeAdditionalData(continueEscaped.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorInvalidClient The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorInvalidClient(writer: SerializationWriter, errorInvalidClient: Partial<ErrorInvalidClient> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorInvalidClient || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ErrorInvalidClient_error>("error", errorInvalidClient.errorEscaped, serializeErrorInvalidClient_error);
    writer.writeAdditionalData(errorInvalidClient.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorInvalidClient_error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorInvalidClient_error(writer: SerializationWriter, errorInvalidClient_error: Partial<ErrorInvalidClient_error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorInvalidClient_error || isSerializingDerivedType) { return; }
    writer.writeEnumValue<ErrorInvalidClient_error_code>("code", errorInvalidClient_error.code);
    writer.writeStringValue("description", errorInvalidClient_error.description);
    writer.writeAdditionalData(errorInvalidClient_error.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorInvalidRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorInvalidRequest(writer: SerializationWriter, errorInvalidRequest: Partial<ErrorInvalidRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorInvalidRequest || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ErrorInvalidRequest_error>("error", errorInvalidRequest.errorEscaped, serializeErrorInvalidRequest_error);
    writer.writeAdditionalData(errorInvalidRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorInvalidRequest_error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorInvalidRequest_error(writer: SerializationWriter, errorInvalidRequest_error: Partial<ErrorInvalidRequest_error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorInvalidRequest_error || isSerializingDerivedType) { return; }
    writer.writeEnumValue<ErrorInvalidRequest_error_code>("code", errorInvalidRequest_error.code);
    writer.writeStringValue("description", errorInvalidRequest_error.description);
    writer.writeAdditionalData(errorInvalidRequest_error.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorInvalidRotation The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorInvalidRotation(writer: SerializationWriter, errorInvalidRotation: Partial<ErrorInvalidRotation> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorInvalidRotation || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ErrorInvalidRotation_error>("error", errorInvalidRotation.errorEscaped, serializeErrorInvalidRotation_error);
    writer.writeAdditionalData(errorInvalidRotation.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorInvalidRotation_error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorInvalidRotation_error(writer: SerializationWriter, errorInvalidRotation_error: Partial<ErrorInvalidRotation_error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorInvalidRotation_error || isSerializingDerivedType) { return; }
    writer.writeEnumValue<ErrorInvalidRotation_error_code>("code", errorInvalidRotation_error.code);
    writer.writeStringValue("description", errorInvalidRotation_error.description);
    writer.writeAdditionalData(errorInvalidRotation_error.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorRequestDenied The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorRequestDenied(writer: SerializationWriter, errorRequestDenied: Partial<ErrorRequestDenied> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorRequestDenied || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ErrorRequestDenied_error>("error", errorRequestDenied.errorEscaped, serializeErrorRequestDenied_error);
    writer.writeAdditionalData(errorRequestDenied.additionalData);
}
/**
 * Serializes information the current object
 * @param ErrorRequestDenied_error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorRequestDenied_error(writer: SerializationWriter, errorRequestDenied_error: Partial<ErrorRequestDenied_error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorRequestDenied_error || isSerializingDerivedType) { return; }
    writer.writeEnumValue<ErrorRequestDenied_error_code>("code", errorRequestDenied_error.code);
    writer.writeStringValue("description", errorRequestDenied_error.description);
    writer.writeAdditionalData(errorRequestDenied_error.additionalData);
}
/**
 * Serializes information the current object
 * @param InteractRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInteractRequest(writer: SerializationWriter, interactRequest: Partial<InteractRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!interactRequest || isSerializingDerivedType) { return; }
    writer.writeObjectValue<InteractRequest_finish>("finish", interactRequest.finish, serializeInteractRequest_finish);
    if(interactRequest.start)
    writer.writeCollectionOfEnumValues<InteractRequest_start>("start", interactRequest.start);
    writer.writeAdditionalData(interactRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param InteractRequest_finish The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInteractRequest_finish(writer: SerializationWriter, interactRequest_finish: Partial<InteractRequest_finish> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!interactRequest_finish || isSerializingDerivedType) { return; }
    writer.writeEnumValue<InteractRequest_finish_method>("method", interactRequest_finish.method);
    writer.writeStringValue("nonce", interactRequest_finish.nonce);
    writer.writeStringValue("uri", interactRequest_finish.uri);
    writer.writeAdditionalData(interactRequest_finish.additionalData);
}
/**
 * Serializes information the current object
 * @param InteractResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInteractResponse(writer: SerializationWriter, interactResponse: Partial<InteractResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!interactResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("finish", interactResponse.finish);
    writer.writeStringValue("redirect", interactResponse.redirect);
    writer.writeAdditionalData(interactResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LimitsOutgoing The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLimitsOutgoing(writer: SerializationWriter, limitsOutgoing: Partial<LimitsOutgoingMember1 | LimitsOutgoingMember2 | LimitsOutgoingMember3> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeLimitsOutgoingMember1(writer, limitsOutgoing as LimitsOutgoingMember1);
    serializeLimitsOutgoingMember2(writer, limitsOutgoing as LimitsOutgoingMember2);
    serializeLimitsOutgoingMember3(writer, limitsOutgoing as LimitsOutgoingMember3);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LimitsOutgoingMember1 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLimitsOutgoingMember1(writer: SerializationWriter, limitsOutgoingMember1: Partial<LimitsOutgoingMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!limitsOutgoingMember1 || isSerializingDerivedType) { return; }
    writer.writeStringValue("interval", limitsOutgoingMember1.interval);
    writer.writeStringValue("receiver", limitsOutgoingMember1.receiver);
    writer.writeAdditionalData(limitsOutgoingMember1.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LimitsOutgoingMember2 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLimitsOutgoingMember2(writer: SerializationWriter, limitsOutgoingMember2: Partial<LimitsOutgoingMember2> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!limitsOutgoingMember2 || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Amount>("debitAmount", limitsOutgoingMember2.debitAmount, serializeAmount);
    writer.writeStringValue("interval", limitsOutgoingMember2.interval);
    writer.writeStringValue("receiver", limitsOutgoingMember2.receiver);
    writer.writeAdditionalData(limitsOutgoingMember2.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LimitsOutgoingMember3 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLimitsOutgoingMember3(writer: SerializationWriter, limitsOutgoingMember3: Partial<LimitsOutgoingMember3> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!limitsOutgoingMember3 || isSerializingDerivedType) { return; }
    writer.writeStringValue("interval", limitsOutgoingMember3.interval);
    writer.writeObjectValue<Amount>("receiveAmount", limitsOutgoingMember3.receiveAmount, serializeAmount);
    writer.writeStringValue("receiver", limitsOutgoingMember3.receiver);
    writer.writeAdditionalData(limitsOutgoingMember3.additionalData);
}
export const AccessIncoming_actionsObject = {
    Create: "create",
    Complete: "complete",
    Read: "read",
    ReadAll: "read-all",
    List: "list",
    ListAll: "list-all",
} as const;
/**
 * The type of resource request as a string.  This field defines which other fields are allowed in the request object.
 */
export const AccessIncoming_typeObject = {
    IncomingPayment: "incoming-payment",
} as const;
export const AccessOutgoing_actionsObject = {
    Create: "create",
    Read: "read",
    ReadAll: "read-all",
    List: "list",
    ListAll: "list-all",
} as const;
/**
 * The type of resource request as a string.  This field defines which other fields are allowed in the request object.
 */
export const AccessOutgoing_typeObject = {
    OutgoingPayment: "outgoing-payment",
} as const;
export const AccessQuote_actionsObject = {
    Create: "create",
    Read: "read",
    ReadAll: "read-all",
} as const;
/**
 * The type of resource request as a string.  This field defines which other fields are allowed in the request object.
 */
export const AccessQuote_typeObject = {
    Quote: "quote",
} as const;
export const ErrorInvalidClient_error_codeObject = {
    Invalid_client: "invalid_client",
} as const;
export const ErrorInvalidRequest_error_codeObject = {
    Invalid_request: "invalid_request",
} as const;
export const ErrorInvalidRotation_error_codeObject = {
    Invalid_rotation: "invalid_rotation",
} as const;
export const ErrorRequestDenied_error_codeObject = {
    Request_denied: "request_denied",
} as const;
/**
 * The callback method that the AS will use to contact the client instance.
 */
export const InteractRequest_finish_methodObject = {
    Redirect: "redirect",
} as const;
export const InteractRequest_startObject = {
    Redirect: "redirect",
} as const;
/* tslint:enable */
/* eslint-enable */
