/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { TokenItemRequestBuilderRequestsMetadata, type TokenItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /token
 */
export interface TokenRequestBuilder extends BaseRequestBuilder<TokenRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.token.item collection
     * @param id Unique identifier of the item
     * @returns {TokenItemRequestBuilder}
     */
     byId(id: string) : TokenItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TokenRequestBuilderUriTemplate = "{+baseurl}/token";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TokenRequestBuilderNavigationMetadata: Record<Exclude<keyof TokenRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: TokenItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/* tslint:enable */
/* eslint-enable */
