/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { DidJsonRequestBuilderRequestsMetadata, type DidJsonRequestBuilder } from './didJson/index.js';
// @ts-ignore
import { JwksJsonRequestBuilderRequestsMetadata, type JwksJsonRequestBuilder } from './jwksJson/index.js';
// @ts-ignore
import { createWalletAddressFromDiscriminatorValue, type WalletAddress } from './models/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestAdapter, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface AuthClient extends BaseRequestBuilder<AuthClient> {
    /**
     * The didJson property
     */
    get didJson(): DidJsonRequestBuilder;
    /**
     * The jwksJson property
     */
    get jwksJson(): JwksJsonRequestBuilder;
    /**
     * Retrieve the public information of the Wallet Address.This end-point should be open to anonymous requests as it allows clients to verify a Wallet Address URL and get the basic information required to construct new transactions and discover the grant request URL.The content should be slow changing and cacheable for long periods. Servers SHOULD use cache control headers.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WalletAddress>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WalletAddress | undefined>;
    /**
     * Retrieve the public information of the Wallet Address.This end-point should be open to anonymous requests as it allows clients to verify a Wallet Address URL and get the basic information required to construct new transactions and discover the grant request URL.The content should be slow changing and cacheable for long periods. Servers SHOULD use cache control headers.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Instantiates a new {@link AuthClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createAuthClient(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
        parseNodeFactoryRegistry.registerDefaultDeserializer(JsonParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(TextParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(FormParseNodeFactory, backingStoreFactory);
    }
    
    if (serializationWriterFactory.registerDefaultSerializer) {
        serializationWriterFactory.registerDefaultSerializer(JsonSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(TextSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(FormSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(MultipartSerializationWriterFactory);
    }
    
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://ilp.interledger-test.dev/alice";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<AuthClient>(requestAdapter, pathParameters, AuthClientNavigationMetadata, AuthClientRequestsMetadata);
}
/**
 * Uri template for the request builder.
 */
export const AuthClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuthClientNavigationMetadata: Record<Exclude<keyof AuthClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    didJson: {
        requestsMetadata: DidJsonRequestBuilderRequestsMetadata,
    },
    jwksJson: {
        requestsMetadata: JwksJsonRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AuthClientRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AuthClientUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createWalletAddressFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
