/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { IncomingPaymentsRequestBuilderNavigationMetadata, IncomingPaymentsRequestBuilderRequestsMetadata, type IncomingPaymentsRequestBuilder } from './incomingPayments/index.js';
// @ts-ignore
import { OutgoingPaymentsRequestBuilderNavigationMetadata, OutgoingPaymentsRequestBuilderRequestsMetadata, type OutgoingPaymentsRequestBuilder } from './outgoingPayments/index.js';
// @ts-ignore
import { QuotesRequestBuilderNavigationMetadata, QuotesRequestBuilderRequestsMetadata, type QuotesRequestBuilder } from './quotes/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * Instantiates a new {@link ResourceClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createResourceClient(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
        parseNodeFactoryRegistry.registerDefaultDeserializer(JsonParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(TextParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(FormParseNodeFactory, backingStoreFactory);
    }
    
    if (serializationWriterFactory.registerDefaultSerializer) {
        serializationWriterFactory.registerDefaultSerializer(JsonSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(TextSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(FormSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(MultipartSerializationWriterFactory);
    }
    
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://ilp.interledger-test.dev";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<ResourceClient>(requestAdapter, pathParameters, ResourceClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface ResourceClient extends BaseRequestBuilder<ResourceClient> {
    /**
     * The incomingPayments property
     */
    get incomingPayments(): IncomingPaymentsRequestBuilder;
    /**
     * Create a new outgoing payment at the wallet address.
     */
    get outgoingPayments(): OutgoingPaymentsRequestBuilder;
    /**
     * Create a new quote at the wallet address.
     */
    get quotes(): QuotesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ResourceClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ResourceClientNavigationMetadata: Record<Exclude<keyof ResourceClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    incomingPayments: {
        requestsMetadata: IncomingPaymentsRequestBuilderRequestsMetadata,
        navigationMetadata: IncomingPaymentsRequestBuilderNavigationMetadata,
    },
    outgoingPayments: {
        requestsMetadata: OutgoingPaymentsRequestBuilderRequestsMetadata,
        navigationMetadata: OutgoingPaymentsRequestBuilderNavigationMetadata,
    },
    quotes: {
        requestsMetadata: QuotesRequestBuilderRequestsMetadata,
        navigationMetadata: QuotesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
