/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDidDocumentFromDiscriminatorValue, type DidDocument } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /did.json
 */
export interface DidJsonRequestBuilder extends BaseRequestBuilder<DidJsonRequestBuilder> {
    /**
     * Retrieve the DID Document of the Wallet Address.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DidDocument>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DidDocument | undefined>;
    /**
     * Retrieve the DID Document of the Wallet Address.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DidJsonRequestBuilderUriTemplate = "{+baseurl}/did.json";
/**
 * Metadata for all the requests in the request builder.
 */
export const DidJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DidJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createDidDocumentFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
