/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DidDocument}
 */
// @ts-ignore
export function createDidDocumentFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDidDocument;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JsonWebKey}
 */
// @ts-ignore
export function createJsonWebKeyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJsonWebKey;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JsonWebKeySet}
 */
// @ts-ignore
export function createJsonWebKeySetFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJsonWebKeySet;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WalletAddress}
 */
// @ts-ignore
export function createWalletAddressFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWalletAddress;
}
/**
 * The deserialization information for the current model
 * @param DidDocument The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDidDocument(didDocument: Partial<DidDocument> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param JsonWebKey The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJsonWebKey(jsonWebKey: Partial<JsonWebKey> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "alg": n => { jsonWebKey.alg = n.getEnumValue<JsonWebKey_alg>(JsonWebKey_algObject); },
        "crv": n => { jsonWebKey.crv = n.getEnumValue<JsonWebKey_crv>(JsonWebKey_crvObject); },
        "kid": n => { jsonWebKey.kid = n.getStringValue(); },
        "kty": n => { jsonWebKey.kty = n.getEnumValue<JsonWebKey_kty>(JsonWebKey_ktyObject); },
        "use": n => { jsonWebKey.use = n.getEnumValue<JsonWebKey_use>(JsonWebKey_useObject); },
        "x": n => { jsonWebKey.x = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param JsonWebKeySet The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJsonWebKeySet(jsonWebKeySet: Partial<JsonWebKeySet> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "keys": n => { jsonWebKeySet.keys = n.getCollectionOfObjectValues<JsonWebKey>(createJsonWebKeyFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param WalletAddress The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWalletAddress(walletAddress: Partial<WalletAddress> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "assetCode": n => { walletAddress.assetCode = n.getStringValue(); },
        "assetScale": n => { walletAddress.assetScale = n.getNumberValue(); },
        "authServer": n => { walletAddress.authServer = n.getStringValue(); },
        "id": n => { walletAddress.id = n.getStringValue(); },
        "publicName": n => { walletAddress.publicName = n.getStringValue(); },
        "resourceServer": n => { walletAddress.resourceServer = n.getStringValue(); },
    }
}
/**
 * A DID Document using JSON encoding
 */
export interface DidDocument extends AdditionalDataHolder, Parsable {
}
/**
 * A JWK representation of an Ed25519 Public Key
 */
export interface JsonWebKey extends AdditionalDataHolder, Parsable {
    /**
     * The cryptographic algorithm family used with the key. The only allowed value is `EdDSA`. 
     */
    alg?: JsonWebKey_alg | null;
    /**
     * The crv property
     */
    crv?: JsonWebKey_crv | null;
    /**
     * The kid property
     */
    kid?: string | null;
    /**
     * The kty property
     */
    kty?: JsonWebKey_kty | null;
    /**
     * The use property
     */
    use?: JsonWebKey_use | null;
    /**
     * The base64 url-encoded public key.
     */
    x?: string | null;
}
export type JsonWebKey_alg = (typeof JsonWebKey_algObject)[keyof typeof JsonWebKey_algObject];
export type JsonWebKey_crv = (typeof JsonWebKey_crvObject)[keyof typeof JsonWebKey_crvObject];
export type JsonWebKey_kty = (typeof JsonWebKey_ktyObject)[keyof typeof JsonWebKey_ktyObject];
export type JsonWebKey_use = (typeof JsonWebKey_useObject)[keyof typeof JsonWebKey_useObject];
/**
 * A JSON Web Key Set document according to [rfc7517](https://datatracker.ietf.org/doc/html/rfc7517) listing the keys associated with this wallet address. These keys are used to sign requests made by this wallet address.
 */
export interface JsonWebKeySet extends Parsable {
    /**
     * The keys property
     */
    keys?: JsonWebKey[] | null;
}
/**
 * Serializes information the current object
 * @param DidDocument The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDidDocument(writer: SerializationWriter, didDocument: Partial<DidDocument> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!didDocument || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(didDocument.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JsonWebKey The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJsonWebKey(writer: SerializationWriter, jsonWebKey: Partial<JsonWebKey> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jsonWebKey || isSerializingDerivedType) { return; }
    writer.writeEnumValue<JsonWebKey_alg>("alg", jsonWebKey.alg);
    writer.writeEnumValue<JsonWebKey_crv>("crv", jsonWebKey.crv);
    writer.writeStringValue("kid", jsonWebKey.kid);
    writer.writeEnumValue<JsonWebKey_kty>("kty", jsonWebKey.kty);
    writer.writeEnumValue<JsonWebKey_use>("use", jsonWebKey.use);
    writer.writeStringValue("x", jsonWebKey.x);
    writer.writeAdditionalData(jsonWebKey.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JsonWebKeySet The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJsonWebKeySet(writer: SerializationWriter, jsonWebKeySet: Partial<JsonWebKeySet> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jsonWebKeySet || isSerializingDerivedType) { return; }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WalletAddress The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWalletAddress(writer: SerializationWriter, walletAddress: Partial<WalletAddress> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!walletAddress || isSerializingDerivedType) { return; }
    writer.writeStringValue("assetCode", walletAddress.assetCode);
    writer.writeNumberValue("assetScale", walletAddress.assetScale);
    writer.writeAdditionalData(walletAddress.additionalData);
}
/**
 * A **wallet address** resource is the root of the API and contains the public details of the financial account represented by the Wallet Address that is also the service endpoint URL.
 */
export interface WalletAddress extends AdditionalDataHolder, Parsable {
    /**
     * The assetCode is a code that indicates the underlying asset. An ISO4217 currency code should be used whenever possible. The ISO4217 representation of the US Dollar is USD.
     */
    assetCode?: string | null;
    /**
     * The number of decimal places that defines the scale of the smallest divisible unit for the given asset code. It determines how an integer amount is scaled to derive the actual monetary value. For example, USD has an asset scale of 2 with the smallest unit being 0.01. An integer amount of `1000` with an `assetCode` of `USD` and `assetScale` of `2` translates to $10.00.
     */
    assetScale?: number | null;
    /**
     * The URL of the authorization server endpoint for getting grants and access tokens for this wallet address.
     */
    authServer?: string | null;
    /**
     * The URL identifying the wallet address.
     */
    id?: string | null;
    /**
     * A public name for the account. This should be set by the account holder with their provider to provide a hint to counterparties as to the identity of the account holder.
     */
    publicName?: string | null;
    /**
     * The URL of the resource server endpoint for performing Open Payments with this wallet address.
     */
    resourceServer?: string | null;
}
/**
 * The cryptographic algorithm family used with the key. The only allowed value is `EdDSA`. 
 */
export const JsonWebKey_algObject = {
    EdDSA: "EdDSA",
} as const;
export const JsonWebKey_crvObject = {
    Ed25519: "Ed25519",
} as const;
export const JsonWebKey_ktyObject = {
    OKP: "OKP",
} as const;
export const JsonWebKey_useObject = {
    Sig: "sig",
} as const;
/* tslint:enable */
/* eslint-enable */
