/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJsonWebKeySetFromDiscriminatorValue, type JsonWebKeySet } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /jwks.json
 */
export interface JwksJsonRequestBuilder extends BaseRequestBuilder<JwksJsonRequestBuilder> {
    /**
     * Retrieve the public keys of the Wallet Address.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JsonWebKeySet>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<JsonWebKeySet | undefined>;
    /**
     * Retrieve the public keys of the Wallet Address.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const JwksJsonRequestBuilderUriTemplate = "{+baseurl}/jwks.json";
/**
 * Metadata for all the requests in the request builder.
 */
export const JwksJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: JwksJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createJsonWebKeySetFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
